### ISSUE TITLE
Automation of sktime's owners or contributors being added in table of contribution lists

### ISSUE THREAD

**Issue by afzal442** [afzal442/DocumentationEnhancementAtsktime#1]
Any ideas do you have? Let's discuss first

**Comment by afzal442** [comment]
Hi @tobyhodges @abdulelahsm , since we are able to print our result directly, I'm not able to store the result in a list and then print it as a list of class_name + author_name.

The Code I tried to run but est doesn't print the result into list, plz have a look:

```
from sktime.utils import all_estimators
from importlib import import_module

est = []
estimators = all_estimators(estimator_types="classifier")
for modname, modclass in estimators:
    try:
        est = [(modname, modclass.__author__)]
    except AttributeError:
        try:
            est = [(modname, import_module(modclass.__module__).__author__)]
        except AttributeError:
            est = [(modname, "no author info")]
```
**`est` doesn't print the whole list such as using `print` statement before you shared with us**

**Comment by afzal442** [comment]
Hi @all, I have been able to figure it out why it's not giving the result as expected. Thanks for your patience.

Correct Code would be:
```
from sktime.utils import all_estimators
from importlib import import_module

est = []
estimators = all_estimators(estimator_types="classifier")
for modname, modclass in estimators:
    try:
        est =est+[(modname, modclass.__author__)]
    except AttributeError:
        try:
            est =est+[(modname, import_module(modclass.__module__).__author__)]
        except AttributeError:
            est =est+[(modname, "no author info")]
```

**Comment by tobyhodges** [comment]
Looks good @afzal442.

However, if you are anyway writing this info to a CSV file you do not need to create a complete list of the estimator-author info. You can write the info one line at a time to the CSV file as you find it, i.e.

```python
with open('author_info.csv', 'w') as outfh:
    for modname, modclass in estimators:
        try:
            outfh.write(f'{modname},{modclass.__author__)}\n')
        except AttributeError:
            try:
                outfh.write(f'{modname},{import_module(modclass.__module__).__author__)}\n')
            except AttributeError:
                outfh.write(f'{modname},no author info\n')
```

If you want to do some other filtering on the info before creating the CSV, then it is indeed better to create the list.

Finally, have you thought about what you will do with the cases where there are multiple authors for an estimator/module? I.e. when the `__author__` attribute contains a list rather than a string?

**Comment by afzal442** [comment]
> Finally, have you thought about what you will do with the cases where there are multiple authors for an estimator/module? I.e. when the `__author__` attribute contains a list rather than a string?

I tried somehow, you could refer to this link https://github.com/alan-turing-institute/sktime/issues/704#issuecomment-842561825 Thanks.

**Comment by afzal442** [comment]
With regards to https://github.com/afzal442/DocumentationEnhancementAtsktime/issues/1#issuecomment-842948936, I feel sorry for being ignorant there. Thanks @tobyhodges for investing your time to make the `__author__` attribute standardised. I had a look at `when the __author__ attribute contains a list rather than a string? `but made it WIP later. But it looks pretty fine now after your effort. You deserve this.

**Comment by tobyhodges** [comment]
Nothing to apologise for @afzal442. I'm glad I could help. Please keep sharing your code when you get stuck and I will do my best to help out.

What's the next step? Will you try to include the CSV file as a table in the `sktime` documentation pages? Or is there another part of the project that takes priority?

**Comment by afzal442** [comment]
Oh yes sure Toby, I would. Thanks. I was just thinking about our next steps. So it will be to integrate with API reference: https://www.sktime.org/en/latest/api_reference.html so as to show the author's list within the table. Else we can think of alternative to include the CSV file directly as a table in the sktime documentation pages like this one as a reference https://mlr3extralearners.mlr-org.com/articles/learners/list_learners.html and https://mlr3extralearners.mlr-org.com/articles/learners/learner_status.html.

**Comment by afzal442** [comment]
```python
from sktime.utils import all_estimators 
from importlib import import_module 
import csv 
m = [m for m, klass in  all_estimators(estimator_types="classifier")]
n = [n for n, klass in  all_estimators(estimator_types="regressor")] 
i = 0 
j = 0
with open("author_list.csv", "w+", newline='') as csvfile: 
     write = csv.writer(csvfile, delimiter=",")  
     write.writerow(["Class_Name","Class_ID","Estimator_Types", "Authors"])
     for modname, modclass in all_estimators():
         try:
             
             if (modname == m[i]):
                  
                 write = csv.writer(csvfile, delimiter = ",") 
                 write.writerow([modname,modclass,"classifier",modclass.__author__])
                 i = i + 1
             elif (modname == n[j] and j < len(n)-1):
                 write = csv.writer(csvfile, delimiter = ",") 
                 write.writerow([modname,modclass,"regressor", modclass.__author__])
                 j = j + 1
             else:
                 write = csv.writer(csvfile, delimiter = ",") 
                 write.writerow([modname,modclass,"forecaster", modclass.__author__]) 
         except AttributeError:
             
             try:
                 
                 if (modname == m[i]):
                     
                     write = csv.writer(csvfile, delimiter = ",") 
                     write.writerow([modname,modclass,"classifier",str(import_module(modclass.__module__).__author__)])
                     i = i + 1
                 
                 if (modname == n[j] and j < len(n)-1):
                      write = csv.writer(csvfile, delimiter = ",")  
                      write.writerow([modname,modclass,"regressor",str(import_module(modclass.__module__).__author__)])
                      j = j + 1    
             except AttributeError:
                 if (modname == m[i]):
                     write = csv.writer(csvfile, delimiter = ",")
                     write.writerow([modname,modclass,"classifier", "no author info"])
                     i = i + 1
                 elif (modname == n[j] and j < len(n)-1):
                     write = csv.writer(csvfile, delimiter = ",")
                     write.writerow([modname,modclass,"regressor", "no author info"])
                     j = j + 1
                 else:
                 
                     write = csv.writer(csvfile, delimiter = ",") 
                     write.writerow([modname,modclass,"forecaster", "no author info"])
```

The above code adds estimators types as well. Just for the shake of estimator's types. Thanks.

**Comment by tobyhodges** [comment]
Nice @afzal442! Good to see you pulling out the type of algorithm for an additional column in the table 👍 

I reviewed the code and there are a few lines you can remove to further improve the performance:

```Python
from sktime.utils import all_estimators
from importlib import import_module
import csv

m = [m for m, klass in  all_estimators(estimator_types="classifier")]
n = [n for n, klass in  all_estimators(estimator_types="regressor")]

with open("author_list.csv", "w+", newline='') as csvfile:
    write = csv.writer(csvfile, delimiter=",") # this line is needed only once, to create the 'write' object that will be used to add data to the CSV file
    write.writerow(["Class_Name","Class_ID","Estimator_Types", "Authors"])
    for modname, modclass in all_estimators():
        try:
            if modname in m: # check whether the module is in the list of classifiers
                write.writerow([modname,modclass,"classifier",modclass.__author__])
            elif modname in n: # or the list of regressors
                write.writerow([modname,modclass,"regressor", modclass.__author__])
            else:
                write.writerow([modname,modclass,"forecaster", modclass.__author__])
        except AttributeError:
            try:
                if modname in m:
                    write.writerow([modname,modclass,"classifier",str(import_module(modclass.__module__).__author__)])
                elif modname in n:
                     write.writerow([modname,modclass,"regressor",str(import_module(modclass.__module__).__author__)])
                else:
                    write.writerow([modname,modclass,"forecaster", "no author info"])
            except AttributeError:
                if modname in m:
                    write.writerow([modname,modclass,"classifier", "no author info"])
                elif modname in n:
                    write.writerow([modname,modclass,"regressor", "no author info"])
                else:
                    write.writerow([modname,modclass,"forecaster", "no author info"])
```

However, https://github.com/alan-turing-institute/sktime/issues/704#issuecomment-844036119 included a desire for the subtype of algorithm e.g. _classification->distance-based_ and I wonder whether we can achieve this (and reduce the number of separate calls to `all_estimators()`) by pulling this information out of the full class string. 

For example, for the `TemporalDictionaryEnsemble` function, the class string is `<class 'sktime.classification.dictionary_based._tde.TemporalDictionaryEnsemble'>` and the type and subtype of the algorithm is _classification->dictionary-based_. That corresponds to the middle parts of that class string i.e. with `sktime`, and `_tde.TemporalDictionaryEnsemble` removed. 

If you can find a way to pull this information directly out of the class string, you would be able to include this subtype information in the table for each algorithm, and simultaneously remove the need for the creation of the `m` and `n` lists above.

**Comment by tobyhodges** [comment]
Finally, if you are working with that class string, is there a way that you can match up the information there with the lines in [the project's `CODEOWNERS` file](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS)? e.g. (again, for `TemporalDictionaryEnsemble`):

```CODEOWNERS
sktime/classification/dictionary_based/ @patrickzib @MatthewMiddlehurst @TonyBagnall
```

**Comment by afzal442** [comment]
Thanks Sir, for reviewing, debugging, cleaning the bit messy code.

> I wonder whether we can achieve this (and reduce the number of separate calls to `all_estimators()`) by pulling this information out of the full class string

Ah yes we can. I think we need to consider `modclass` as a string to extract the required info out of that. And that will be a nice approach to make things more clear as is desired. As I can see in the above code I also missed out about transformer class as well if it is so.

As of now, we are able to add the below fields into the table:

- [x] class name,
- [x] class id
- [x] scitype (e.g. forecaster, classifier, etc.),
- [x] original contributor,
- [x] algorithm type,
- [ ] maintainer/current code owner,
- [ ] link to API reference,

**Comment by afzal442** [comment]
> Finally, if you are working with that class string, is there a way that you can match up the information there with the lines in [the project's `CODEOWNERS` file](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS)? e.g. (again, for `TemporalDictionaryEnsemble`)

I am afraid I can't find any way out of this for now. I wanted to ask you about this earlier. So I need your suggestion for this if any.

**Comment by tobyhodges** [comment]
I think this could be achieved with a couple of functions:

1. a function to read and process the contents of `CODEOWNERS`. The result could be a dictionary, keyed by paths, with values as lists of usernames for the owners of the code at each path. This means that the function would read these lines:

```CODEOWNERS
sktime/classification/distance_based/ @jasonlines @goaster @TonyBagnall
sktime/classification/dictionary_based/ @patrickzib @MatthewMiddlehurst @TonyBagnall
sktime/classification/dictionary_based/tests @patrickzib
```

and turn it into

```Python
{ "sktime/classification/distance_based" : ["jasonlines", "goaster", "TonyBagnall"],
  "sktime/classification/dictionary_based" : ["patrickzib", "MatthewMiddlehurst", "TonyBagnall"],
  "sktime/classification/dictionary_based/tests" : ["patrickzib"] }
```

2. a function to compare the components of the class string to the paths in this dictionary, returning the GitHub username(s) of the code owner(s) for that class (where possible). This second function is likely to need some careful design, because there are several edge cases in that CODEOWNERs file that could trip it up, e.g. some paths finish with <filename>.py, some are subpaths of paths already described in the file (compare the second and third lines in the example above to see what I mean), some lines are blank, etc...

**Comment by afzal442** [comment]
Oh thanks cool! Alright. We can achieve that in those following ways. I think we can tell Markus to remove .py linked with some of the class strings. Sencondly, we need gh username in the codeowner field as above you mentioned.

**Comment by afzal442** [comment]
I will let you know the first task on how to extract `algorithm type` out of each class string, once I am done or if I can achieve something. Thanks

**Comment by afzal442** [comment]
@tobyhodges I wanted to know if there is a way to automate CODEOWNER's [file](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS)? Just to segregate this [issue] https://github.com/alan-turing-institute/sktime/issues/704#issuecomment-846417584. The related file to be considered will be [estimator overview](https://github.com/alan-turing-institute/sktime/blob/main/ESTIMATOR_OVERVIEW.md).

**Comment by afzal442** [comment]
Next step:
- Could we integrate reactable here in this repo to see the result locally?
- Update the [estimator overview file](https://github.com/alan-turing-institute/sktime/blob/main/ESTIMATOR_OVERVIEW.md) to be assigned to Abdul
- Integrate HTML files using this format https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through
- csvtotable repo link https://github.com/vividvilla/csvtotable/blob/master/csvtotable/convert.py

**Comment by tobyhodges** [comment]
This Python library can create an interactive table from a CSV: https://github.com/vividvilla/csvtotable Might be worth exploring when you have some time to spare... As this produces an HTML file, it _may_ be possible to tell Sphinx to include it on a page somewhere. **If** `csvtotable` works, and **if** you can insert HTML into RST pages with Sphinx, you would be able to host your interactive table in the `sktime` docs directly.

> @tobyhodges I wanted to know if there is a way to automate CODEOWNER's file? 

you mean to automate the creation of the CODEOWNERs file? I am not aware of anything that would do this but it is at least possible (but pretty complicated) in theory!

**Comment by afzal442** [comment]
Closing for #3
